package com.mycompany.pizzaplanet.View;

import com.mycompany.pizzaplanet.Controller.ClienteController;
import com.mycompany.pizzaplanet.Controller.PedidoController;
import com.mycompany.pizzaplanet.Model.BancoDeDados;
import com.mycompany.pizzaplanet.Model.Cliente;
import com.mycompany.pizzaplanet.Model.Pedido;
import com.mycompany.pizzaplanet.Model.Pizza;
import com.mycompany.pizzaplanet.Model.Produto;
import com.mycompany.pizzaplanet.Model.Tamanho;
import com.mycompany.pizzaplanet.View.Ingredientes.GerenciamentoIngrediente;
import com.mycompany.pizzaplanet.View.Pizzas.GerenciamentoPizza;
import com.mycompany.pizzaplanet.View.Produtos.GerenciamentoProduto;
import com.mycompany.pizzaplanet.View.Tamanhos.GerenciamentoTamanho;
import java.io.IOException;
import javax.swing.DefaultListModel;

public class DashboardAdm extends javax.swing.JFrame {

    public Pedido pedidoLista = new Pedido();
    public Pedido pedidoListaProducao = new Pedido();
    /**
     * Creates new form DashboardAdm
     */
    public DashboardAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPedidoSolicitado = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeClienteListSoli = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEnderecoClienteListSoli = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTamanhoListSoli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnEnviarProducao = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listPizzaSoli = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        txtProdSoli = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPedidosProducao = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtNomeClienteProducao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEnderecoClienteProducao = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTamanhoProducao = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnFinalizaPedidoProducao = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        listPizzaProducao = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtValorTotalProducao = new javax.swing.JTextField();
        txtProdProducao = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtFormaPagamentoProducao = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel1.setText("Bem vindo!!");

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel6.setText("Pedidos Solicitados");

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel7.setText("Pedidos em Produção");

        listPedidoSolicitado.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        listPedidoSolicitado.setMaximumSize(new java.awt.Dimension(70, 95));
        listPedidoSolicitado.setPreferredSize(new java.awt.Dimension(60, 95));
        listPedidoSolicitado.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                listPedidoSolicitadoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        listPedidoSolicitado.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listPedidoSolicitadoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listPedidoSolicitado);

        jPanel1.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel2.setText("Nome:");

        txtNomeClienteListSoli.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        txtNomeClienteListSoli.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel3.setText("Endereço:");

        txtEnderecoClienteListSoli.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        txtEnderecoClienteListSoli.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel4.setText("Tamanho Pizza:");

        txtTamanhoListSoli.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        txtTamanhoListSoli.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel5.setText("Pizzas Solicitadas:");

        btnEnviarProducao.setText("Enviar para Produção");
        btnEnviarProducao.setEnabled(false);
        btnEnviarProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarProducaoActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(listPizzaSoli);

        jLabel15.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel15.setText("Produtos Adicionais:");

        txtProdSoli.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(txtProdSoli, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTamanhoListSoli, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                    .addComponent(txtEnderecoClienteListSoli)
                    .addComponent(txtNomeClienteListSoli)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEnviarProducao)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeClienteListSoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEnderecoClienteListSoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTamanhoListSoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProdSoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnEnviarProducao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listPedidosProducao.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        listPedidosProducao.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                listPedidosProducaoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        listPedidosProducao.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listPedidosProducaoValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listPedidosProducao);

        jLabel8.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel8.setText("Nome:");

        txtNomeClienteProducao.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        txtNomeClienteProducao.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel9.setText("Endereço:");

        txtEnderecoClienteProducao.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        txtEnderecoClienteProducao.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel10.setText("Tamanho Pizza:");

        txtTamanhoProducao.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        txtTamanhoProducao.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel11.setText("Pizzas Solicitadas:");

        btnFinalizaPedidoProducao.setText("Finalizar Pedido");
        btnFinalizaPedidoProducao.setEnabled(false);
        btnFinalizaPedidoProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizaPedidoProducaoActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(listPizzaProducao);

        jLabel14.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel14.setText("Produtos Adicionais");

        jLabel13.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel13.setText("Valor Total:");

        txtValorTotalProducao.setEnabled(false);

        txtProdProducao.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel16.setText("Método de Pagamento:");

        txtFormaPagamentoProducao.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeClienteProducao)
                            .addComponent(txtEnderecoClienteProducao)
                            .addComponent(txtTamanhoProducao)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(btnFinalizaPedidoProducao))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(76, 76, 76))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProdProducao)
                            .addComponent(jLabel13)
                            .addComponent(txtValorTotalProducao)
                            .addComponent(jLabel16)
                            .addComponent(txtFormaPagamentoProducao, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeClienteProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEnderecoClienteProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTamanhoProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtProdProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFormaPagamentoProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorTotalProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(btnFinalizaPedidoProducao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N

        jMenu1.setText("Dashboard");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pizzas");

        jMenuItem1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jMenuItem1.setText("Ingredientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jMenuItem2.setText("Tamanhos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jMenuItem3.setText("Gerenciador Pizza");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem3MouseClicked(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Produtos");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Pedidos");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarProducaoActionPerformed
        // TODO add your handling code here:
        try {
            PedidoController.alteraStatusPedido(pedidoLista,"Em Produção");
//            PedidoController.deletaPedidoSolicitado(pedidoLista);
            
            BancoDeDados banco = new BancoDeDados();
//            BancoDeDados.leBDPedidoProducao(BancoDeDados.getBancoPedidoProducao());
            BancoDeDados.leBDPedido(BancoDeDados.getBancoPedido());
            
            //cria o modelo da lista de produção
            DefaultListModel model = new DefaultListModel();
            for(Pedido pedidoProducao : Pedido.getListaPedidos()) {
                if(pedidoProducao.getStatus().equals("Em Produção")) {
                    System.out.println(pedidoProducao.getCliente().getNome());
                    model.addElement(pedidoProducao.getCliente().getNome());
                }
            }
            listPedidosProducao.setModel(model);
            
            //cria o modelo da lista de pedido solicitado
            DefaultListModel modelSoli = new DefaultListModel();
            for(Pedido pedidoSolicitado : Pedido.getListaPedidos()) {
                if(pedidoSolicitado.getStatus().equals("Solicitado")) {
                    modelSoli.addElement(pedidoSolicitado.getCliente().getNome());
                }
            }
            listPedidoSolicitado.setModel(modelSoli);
            
            //limpando os campos da lista solicitada
            txtNomeClienteListSoli.setText("");
            txtEnderecoClienteListSoli.setText("");
            txtProdSoli.setText("");
            txtTamanhoListSoli.setText("");
            DefaultListModel modelLimpar = new DefaultListModel();
            modelLimpar.setSize(0);
            listPizzaSoli.setModel(modelLimpar);
            
        } catch (IOException e) {
            System.out.println("error");
        }
    }//GEN-LAST:event_btnEnviarProducaoActionPerformed

    private void btnFinalizaPedidoProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizaPedidoProducaoActionPerformed
        // TODO add your handling code here:
        try {
            PedidoController.alteraStatusPedido(pedidoListaProducao,"Finalizado");
            
            BancoDeDados banco = new BancoDeDados();
            BancoDeDados.leBDPedido(BancoDeDados.getBancoPedido());
          
            //cria o modelo da lista de produção
            DefaultListModel model = new DefaultListModel();
            for(Pedido pedidoProducao : Pedido.getListaPedidos()) {
                if(pedidoProducao.getStatus().equals("Em Produção")) {
                    System.out.println(pedidoProducao.getCliente().getNome());
                    model.addElement(pedidoProducao.getCliente().getNome());
                }
            }
            listPedidosProducao.setModel(model);
            
            //limpa os campos dos inputs
            txtNomeClienteProducao.setText("");
            txtEnderecoClienteProducao.setText("");
            txtTamanhoProducao.setText("");
            txtProdProducao.setText("");
            txtFormaPagamentoProducao.setText("");
            txtValorTotalProducao.setText("");
            
            DefaultListModel modelLimpa = new DefaultListModel();
            modelLimpa.setSize(0);
            listPizzaProducao.setModel(modelLimpa);
            
        } catch (IOException e) {
            System.out.println("error");
        }
        
    }//GEN-LAST:event_btnFinalizaPedidoProducaoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        GerenciamentoTamanho indexT = new GerenciamentoTamanho();
        indexT.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        GerenciamentoIngrediente indexIngre = new GerenciamentoIngrediente();
        indexIngre.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
            // TODO add your handling code here:
        this.dispose();
        GerenciamentoProduto indexT = new GerenciamentoProduto();
        indexT.setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        GerenciamentoPizza indexP = new GerenciamentoPizza();
        indexP.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MouseClicked
        // TODO add your handling code here:
        this.dispose();
        GerenciamentoPizza indexP = new GerenciamentoPizza();
        indexP.setVisible(true);
    }//GEN-LAST:event_jMenuItem3MouseClicked

    private void listPedidoSolicitadoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_listPedidoSolicitadoAncestorAdded
        // TODO add your handling code here:
        try {
            BancoDeDados banco = new BancoDeDados();
            BancoDeDados.leBDPedido(BancoDeDados.getBancoPedido());
            DefaultListModel model = new DefaultListModel();
            model.setSize(0);
            for(Pedido pedido : Pedido.getListaPedidos()) {
                if(pedido.getStatus().equals("Solicitado")) {
                    model.addElement(pedido.getCliente().getNome());
                }
            }
            listPedidoSolicitado.setModel(model);
        } catch (IOException e) {
            System.out.println("error");
        }
    }//GEN-LAST:event_listPedidoSolicitadoAncestorAdded

    private void selecionaPedido(String nomeCliente) {
        
        try {
            BancoDeDados banco = new BancoDeDados();
            BancoDeDados.leBDPedido(BancoDeDados.getBancoPedido());
            
            for(Pedido pedido : Pedido.getListaPedidos()) {
                if(nomeCliente.equals(pedido.getCliente().getNome())) {
                    pedidoLista = pedido;
                    break;
                }
            }
            
        } catch(IOException e) {
            System.out.println("error");
        }
    }
    
    private void selecionaPedidoProducao(String nomeCliente) {
        try {
            BancoDeDados banco = new BancoDeDados();
            BancoDeDados.leBDPedido(BancoDeDados.getBancoPedido());
            
            for(Pedido pedido : Pedido.getListaPedidos()) {
                if(nomeCliente.equals(pedido.getCliente().getNome()) && pedido.getStatus().equals("Em Produção")) {
                    pedidoListaProducao = pedido;
                    break;
                }
            }
            
        } catch(IOException e) {
            System.out.println("error");
        }
    }
    
    private void listPedidoSolicitadoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listPedidoSolicitadoValueChanged
        // TODO add your handling code here:
        if(listPedidoSolicitado.getSelectedValue() != null) {
            //pega o pedido de acordo com o nome do cliente na lista
            selecionaPedido(listPedidoSolicitado.getSelectedValue());
            //seta os valores dos inputs
            txtNomeClienteListSoli.setText(pedidoLista.getCliente().getNome());
            txtEnderecoClienteListSoli.setText(pedidoLista.getCliente().getEndereco().getRua()+" "+pedidoLista.getCliente().getEndereco().getNumero()+" "+pedidoLista.getCliente().getEndereco().getBairro()+" "+pedidoLista.getCliente().getEndereco().getCidade());
            txtTamanhoListSoli.setText(pedidoLista.getTamanho().getNome());
            
            //setando a lista de pizza
            DefaultListModel model = new DefaultListModel();
            model.setSize(0);
            for(Pizza pizza : pedidoLista.getPizza()) {
                model.addElement(pizza.getNome());
            }
            listPizzaSoli.setModel(model);
            
            //setando input de produtos adicionais caso tenha
            if(pedidoLista.getProduto() != null) {
                txtProdSoli.setText(pedidoLista.getProduto().getNome());
            }
            
            //habilitando o botão de enviar para produção
            btnEnviarProducao.setEnabled(true);
        }
    }//GEN-LAST:event_listPedidoSolicitadoValueChanged

    private void listPedidosProducaoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_listPedidosProducaoAncestorAdded
        // TODO add your handling code here:
        try {
            BancoDeDados banco = new BancoDeDados();
            BancoDeDados.leBDPedido(BancoDeDados.getBancoPedido());
            DefaultListModel model = new DefaultListModel();
            model.setSize(0);
            for(Pedido pedido : Pedido.getListaPedidos()) {
                if(pedido.getStatus().equals("Em Produção")) {
                    System.out.println("FFFFFOOOOII");
                    model.addElement(pedido.getCliente().getNome());
                }
            }
            listPedidosProducao.setModel(model);
        } catch (IOException e) {
            System.out.println("error");
        }
    }//GEN-LAST:event_listPedidosProducaoAncestorAdded

    private void listPedidosProducaoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listPedidosProducaoValueChanged
        // TODO add your handling code here:
        if(listPedidosProducao.getSelectedValue() != null) {
            //pega o pedido de acordo com o nome do cliente na lista
            selecionaPedidoProducao(listPedidosProducao.getSelectedValue());
            //seta os valores dos inputs
            txtNomeClienteProducao.setText(pedidoListaProducao.getCliente().getNome());
            txtEnderecoClienteProducao.setText(pedidoListaProducao.getCliente().getEndereco().getRua()+" "+pedidoListaProducao.getCliente().getEndereco().getNumero()+" "+pedidoListaProducao.getCliente().getEndereco().getBairro()+" "+pedidoListaProducao.getCliente().getEndereco().getCidade());
            txtTamanhoProducao.setText(pedidoListaProducao.getTamanho().getNome());
            txtValorTotalProducao.setText(Double.toString(pedidoListaProducao.getValorTotal()));
            txtFormaPagamentoProducao.setText(pedidoListaProducao.getFormaPagamento());

            if(pedidoListaProducao.getProduto() != null) {
                txtProdProducao.setText(pedidoListaProducao.getProduto().getNome());
            }
            
            //setando a lista de pizza
            DefaultListModel model = new DefaultListModel();
            model.setSize(0);
            for(Pizza pizza : pedidoListaProducao.getPizza()) {
                model.addElement(pizza.getNome());
            }
            listPizzaProducao.setModel(model);
            
            //habilitando o botão de enviar para produção
            btnFinalizaPedidoProducao.setEnabled(true);
        }
    }//GEN-LAST:event_listPedidosProducaoValueChanged
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarProducao;
    private javax.swing.JButton btnFinalizaPedidoProducao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> listPedidoSolicitado;
    private javax.swing.JList<String> listPedidosProducao;
    private javax.swing.JList<String> listPizzaProducao;
    private javax.swing.JList<String> listPizzaSoli;
    private javax.swing.JTextField txtEnderecoClienteListSoli;
    private javax.swing.JTextField txtEnderecoClienteProducao;
    private javax.swing.JTextField txtFormaPagamentoProducao;
    private javax.swing.JTextField txtNomeClienteListSoli;
    private javax.swing.JTextField txtNomeClienteProducao;
    private javax.swing.JTextField txtProdProducao;
    private javax.swing.JTextField txtProdSoli;
    private javax.swing.JTextField txtTamanhoListSoli;
    private javax.swing.JTextField txtTamanhoProducao;
    private javax.swing.JTextField txtValorTotalProducao;
    // End of variables declaration//GEN-END:variables
}
