package com.mycompany.pizzaplanet.View.Pedidos;

import com.mycompany.pizzaplanet.Model.BancoDeDados;
import com.mycompany.pizzaplanet.Model.Ingrediente;
import com.mycompany.pizzaplanet.Model.PizzaDoce;
import com.mycompany.pizzaplanet.Model.PizzaSalgada;
import com.mycompany.pizzaplanet.Model.Produto;
import com.mycompany.pizzaplanet.Model.Tamanho;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JRadioButton;

public class FazerPedido extends javax.swing.JFrame {

    public Font fonteCabecalho = new Font("Monospaced", Font.BOLD, 14);
    public Font fonteCorpo = new Font("Monospaced", Font.PLAIN, 12);
    public JRadioButton JRadioButtonTamanho = new JRadioButton();
    public JRadioButton JRadioButtonPizza = new JRadioButton();
    public JRadioButton JRadioButtonProduto = new JRadioButton();
    
    /**
     * Creates new form FazerPedido
     */
    public FazerPedido() {
        initComponents();
        //inicializa o painel dos tamanhos
        panelTamanhosPedido.setLayout(new FlowLayout());
        panelTamanhosPedido.setPreferredSize(new Dimension(300, 200));
        //inicializa o painel dos tamanhos
        panelPizzaPedido.setLayout(new FlowLayout());
        panelPizzaPedido.setPreferredSize(new Dimension(300, 200));
        //inicializa o painel dos tamanhos
        panelProdutoPedido.setLayout(new FlowLayout());
        panelProdutoPedido.setPreferredSize(new Dimension(300, 200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelTamanhosPedido = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelPizzaPedido = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelProdutoPedido = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel1.setText("Escolha o tamanho desejado!");

        panelTamanhosPedido.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                panelTamanhosPedidoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout panelTamanhosPedidoLayout = new javax.swing.GroupLayout(panelTamanhosPedido);
        panelTamanhosPedido.setLayout(panelTamanhosPedidoLayout);
        panelTamanhosPedidoLayout.setHorizontalGroup(
            panelTamanhosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );
        panelTamanhosPedidoLayout.setVerticalGroup(
            panelTamanhosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel2.setText("Escolha a Pizza Desejada!");

        panelPizzaPedido.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                panelPizzaPedidoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout panelPizzaPedidoLayout = new javax.swing.GroupLayout(panelPizzaPedido);
        panelPizzaPedido.setLayout(panelPizzaPedidoLayout);
        panelPizzaPedidoLayout.setHorizontalGroup(
            panelPizzaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelPizzaPedidoLayout.setVerticalGroup(
            panelPizzaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel3.setText("Algum produto adicional?");

        panelProdutoPedido.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                panelProdutoPedidoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout panelProdutoPedidoLayout = new javax.swing.GroupLayout(panelProdutoPedido);
        panelProdutoPedido.setLayout(panelProdutoPedidoLayout);
        panelProdutoPedidoLayout.setHorizontalGroup(
            panelProdutoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelProdutoPedidoLayout.setVerticalGroup(
            panelProdutoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        jButton1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jButton1.setText("Finalizar Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(panelTamanhosPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelPizzaPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelProdutoPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(panelTamanhosPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(panelPizzaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(panelProdutoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jScrollPane1.setViewportView(jPanel1);

        jMenu1.setText("Dashboard");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelPizzaPedidoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_panelPizzaPedidoAncestorAdded
        // TODO add your handling code here:
        try {
            BancoDeDados banco = new BancoDeDados();
            BancoDeDados.leBDPizzaDoce(BancoDeDados.getBancoPizzaDoce());
            for(PizzaDoce pizza : PizzaDoce.getListaPizzasDoces()) {
                int optionNumber = buttonGroup2.getButtonCount() + 1;
                JRadioButton radioButton = new JRadioButton(pizza.getNome());
                radioButton.setFont(fonteCorpo);
                int aux = 0;
                for(Ingrediente ingre : pizza.getListaIngredientes()) {
                    if(aux == 0) {
                        radioButton.setToolTipText("Ingredientes: " + ingre.getNome());
                        aux++;
                    } else {
                        radioButton.setToolTipText(radioButton.getToolTipText() + ", " + ingre.getNome());
                    }
                }
                buttonGroup2.add(radioButton);
                panelPizzaPedido.add(radioButton);
                radioButton.setVisible(true);
                panelPizzaPedido.revalidate();
                panelPizzaPedido.repaint();
                radioButton.addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        Enumeration<AbstractButton> buttons = buttonGroup2.getElements();
                        while (buttons.hasMoreElements()) {
                            AbstractButton button = buttons.nextElement();
                            if (button.isSelected()) {
                                JRadioButtonPizza = (JRadioButton)button;
                                break;
                            }
                        }
                    }
                });
            }

        } catch (IOException e) {
            System.out.println("error");
        }
    }//GEN-LAST:event_panelPizzaPedidoAncestorAdded

    private void panelTamanhosPedidoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_panelTamanhosPedidoAncestorAdded
        // TODO add your handling code here:
        try {
            BancoDeDados banco = new BancoDeDados();
            BancoDeDados.leBDTamanho(BancoDeDados.getBancoTamanho());
            for(Tamanho tamanho : Tamanho.getListaTamanhos()) {
                int optionNumber = buttonGroup1.getButtonCount() + 1;
                JRadioButton radioButton = new JRadioButton(tamanho.getNome());
                radioButton.setFont(fonteCorpo);
                radioButton.setToolTipText("Quant. Pedaços: " + tamanho.getQuantidadePecas() + " - Valor: " + tamanho.getValor());
                buttonGroup1.add(radioButton);
                panelTamanhosPedido.add(radioButton);
                radioButton.setVisible(true);
                panelTamanhosPedido.revalidate();
                panelTamanhosPedido.repaint();
                radioButton.addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        Enumeration<AbstractButton> buttons = buttonGroup1.getElements();
                        while (buttons.hasMoreElements()) {
                            AbstractButton button = buttons.nextElement();
                            if (button.isSelected()) {
                                JRadioButtonTamanho = (JRadioButton)button;
                                break;
                            }
                        }
                    }
                });
            }

        } catch (IOException e) {
            System.out.println("error");
        }
    }//GEN-LAST:event_panelTamanhosPedidoAncestorAdded

    private void panelProdutoPedidoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_panelProdutoPedidoAncestorAdded
        // TODO add your handling code here:
        try {
            BancoDeDados banco = new BancoDeDados();
            BancoDeDados.leBDProduto(BancoDeDados.getBancoProduto());
            for(Produto produto : Produto.getListaProdutos()) {
                int optionNumber = buttonGroup3.getButtonCount() + 1;
                JRadioButton radioButton = new JRadioButton(produto.getNome());
                radioButton.setFont(fonteCorpo);
                radioButton.setToolTipText("Preço: " + produto.getValor());
                buttonGroup3.add(radioButton);
                panelProdutoPedido.add(radioButton);
                radioButton.setVisible(true);
                panelProdutoPedido.revalidate();
                panelProdutoPedido.repaint();
                radioButton.addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        Enumeration<AbstractButton> buttons = buttonGroup3.getElements();
                        while (buttons.hasMoreElements()) {
                            AbstractButton button = buttons.nextElement();
                            if (button.isSelected()) {
                                JRadioButtonProduto = (JRadioButton)button;
                                break;
                            }
                        }
                    }
                });
            }

        } catch (IOException e) {
            System.out.println("error");
        }
    }//GEN-LAST:event_panelProdutoPedidoAncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        try {
//            BancoDeDados banco = new BancoDeDados();
//            BancoDeDados.leBDTamanho(BancoDeDados.getBancoTamanho());
//        } catch (IOException e) {
//            System.out.println("error");
//        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FazerPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FazerPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FazerPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FazerPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FazerPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelPizzaPedido;
    private javax.swing.JPanel panelProdutoPedido;
    private javax.swing.JPanel panelTamanhosPedido;
    // End of variables declaration//GEN-END:variables
}
